### PR TITLE
Fix Issue 156

### LINKED ISSUE #156: Duplicate upload when calling uploadWithFinishedBlock successively
Mentioned in #155.

Duplicate upload when calling uploadWithFinishedBlock multiple times in a row (before an event finishes uploading and gets deleted from sqlite).

### PR DESCRIPTION
**Pull request by baumatron**
Fix threading issues with KeenClient and KIODBStore creation. Use a shared uploader queue across KeenClient instances. Fixes #156.

### CODE REVIEW

File: KeenClient/KeenClient.m [hunk 1]
```diff
@@ -243,37 +241,39 @@ + (void)disableGeoLocationDefaultRequest {
...
+- (instancetype)init {
     self = [super init];
 
-    // log the current version number
-    if ([KeenClient isLoggingEnabled]) {
-        KCLog(@"KeenClient-iOS %@", kKeenSdkVersion);
-    }
+    if (nil != self) {
+        // log the current version number
+        if ([KeenClient isLoggingEnabled]) {
```
Comment (masojus) [inline KeenClient/KeenClient.m]: Why do we check isLoggingEnabled here but not elsewhere. I thought KCLog() performed that check internally. PR #188 changes this a bit, but the check for logging enabled is still handled somewhere down in the logger I think, so it seems like either case this check can go away.

File: KeenClient/KeenClient.m [hunk 2]
```diff
@@ -291,78 +228,140 @@ + (BOOL)validateKey:(NSString *)key {
...
 
-- (id)initWithProjectID:(NSString *)projectID andWriteKey:(NSString *)writeKey andReadKey:(NSString *)readKey {
+- (instancetype)initWithNetwork:(KIONetwork*)network
+                       andStore:(KIODBStore*)store
+                    andUploader:(KIOUploader*)uploader {
+    self = [super init];
+
+    if (nil != self) {
+        // log the current version number
+        if ([KeenClient isLoggingEnabled]) {
```
Comment (masojus) [inline KeenClient/KeenClient.m]: Why do we check isLoggingEnabled here but not elsewhere. I thought KCLog() performed that check internally. PR #188 changes this a bit, but the check for logging enabled is still handled somewhere down in the logger I think, so it seems like either case this check can go away.

File: KeenClient/KeenClient.m [hunk 3]
```diff
@@ -291,78 +228,140 @@ + (BOOL)validateKey:(NSString *)key {
...
     if (![KeenClient validateProjectID:projectID]) {
+        KCLog(@"Invalid projectID: %@", projectID);
         return nil;
     }
 
-    if (!dbStore) {
-        dbStore = [[KIODBStore alloc] init];
+    if (nil != writeKey) {
+        // only validate a non-nil value
+        KCLog(@"Invalid writeKey: %@", writeKey);
```
Comment (masojus) [inline KeenClient/KeenClient.m]: Why is this log message outside the if(!validateKey...) check? Same question below for readKey.

File: KeenClient/KeenClient.m [hunk 4]
```diff
@@ -291,78 +228,140 @@ + (BOOL)validateKey:(NSString *)key {
...
+        KCLog(@"Invalid projectID: %@", projectID);
         return nil;
     }
 
-    if (!dbStore) {
-        dbStore = [[KIODBStore alloc] init];
-    }
-    sharedClient.projectID = projectID;
-
     if (writeKey) {
```
Comment (masojus) [inline KeenClient/KeenClient.m]: Is if(writeKey) fundamentally different from if(nil != writeKey) which is what is done above?

File: KeenClient/KeenClient.m [hunk 5]
```diff
@@ -291,78 +228,140 @@ + (BOOL)validateKey:(NSString *)key {
...
         // only validate a non-nil value
+        KCLog(@"Invalid writeKey: %@", writeKey);
```
Comment (masojus) [inline KeenClient/KeenClient.m]: Why is this log message outside the if(!validateKey...) check? Same question below for readKey.

File: KeenClient/KeenClient.m [hunk 6]
```diff
@@ -596,470 +595,60 @@ - (BOOL)addEvent:(NSDictionary *)event withKeenProperties:(KeenProperties *)keen
...
-                dispatch_async(dispatch_get_main_queue(), ^{
-                    // run the user-specific block (if there is one)
-                    if (block) {
-                        KCLog(@"Running user-specified block.");
-                        @try {
-                            block(data, response, error);
-                        } @finally {
-                            // do nothing
-                        }
+        [self runQuery:keenQuery completionHandler:^(NSData *data, NSURLResponse *response, NSError *error) {
```
Comment (masojus) [inline KeenClient/KeenClient.m]: Is the maxQueryAttempts stuff now handled elsewhere?

File: KeenClient/KeenClient.m [hunk 7]
```diff
@@ -1076,144 +665,18 @@ - (void)runAsyncMultiAnalysisWithQueries:(NSArray *)keenQueries block:(void (^)(
...
-        [request setValue:@"application/json" forHTTPHeaderField:@"Content-Type"];
-        [request setValue:self.readKey forHTTPHeaderField:@"Authorization"];
-        [request setValue:[NSString stringWithFormat:@"%lud",(unsigned long) [[keenQuery convertQueryToData] length]] forHTTPHeaderField:@"Content-Length"];
-        [request setValue:kKeenSdkVersionWithPlatform forHTTPHeaderField:kKeenSdkVersionHeader];
-        [request setHTTPBody:[keenQuery convertQueryToData]];
-
-        NSURLSession *session = [self sharedUrlSession];
-        [[session dataTaskWithRequest:request completionHandler:completionHandler] resume];
-    }
+    [self.network runQuery:keenQuery
```
Comment (masojus) [inline KeenClient/KeenClient.m]: Same question here. I suppose the hasQueryWithMaxAttempts stuff is handled in network module now, right?

File: KeenClientTests/KeenClientTests.m [hunk 8]
```diff
@@ -1964,7 +1988,7 @@ - (NSString *)cacheDirectory {
 }
 
 - (NSString *)keenDirectory {
-    return [[[self cacheDirectory] stringByAppendingPathComponent:@"keen"] stringByAppendingPathComponent:@"id"];
+    return [[[self cacheDirectory] stringByAppendingPathComponent:@"keen"] stringByAppendingPathComponent:kDefaultProjectID];
 }
```
Comment (masojus) [inline KeenClientTests/KeenClientTests.m]: This file is >2000 lines. Similar to what we plan to do with the Java SDK tests, we should look into splitting this apart so it's not quite so unwieldy. Maybe create an Issue? Or just do it at some point... :)

File: KeenClient/KeenClient.h [hunk 9]
```diff
@@ -203,54 +203,56 @@ typedef NSDictionary* (^KeenGlobalPropertiesBlock)(NSString *eventCollection);
 /**
  Call this to indiscriminately delete all events queued for sending.
  */
-+ (void)clearAllEvents;
++ (void)clearAllEvents DEPRECATED_MSG_ATTRIBUTE("Class method clearAllEvents is deprecated. Use instance method instead.");
```
Comment (masojus) [inline KeenClient/KeenClient.h]: So these deprecations are the major (or only?) potentially breaking public interface changes, right? The additional KeenClient init functions for passing in implementations of the other modules (network/uploader/store) are all strictly additive, right? So I imagine the plan is to remove these class methods in the next major release, right?

File: KeenClient/KeenClient.m [hunk 10]
```diff
@@ -75,96 +83,6 @@ + (BOOL)validateProjectID:(NSString *)projectID;
...
- @returns An NSArray* of NSStrings* that are names of sub-files or directories.
- */
-- (NSArray *)contentsAtPath:(NSString *)path;
-
-/**
- Returns the directory for a particular collection where events exist.
- @param collection The collection.
- @returns An NSString* that is a path to the collection directory.
- */
-- (NSString *)eventDirectoryForCollection:(NSString *)collection;
```
Comment (masojus) [inline KeenClient/KeenClient.m]: Thanks for getting rid of this and pathForEventInCollection()! My favorite way to up CC numbers is to delete stuff :)

**Comment by masojus** [comment]
I didn't pore over the code in the new KIOFileStore/KIONetwork/KIOUploader/KIOUtil, since I imagined the bulk of it is mostly ported from what used to be in KeenClient.m. The approach makes sense to me, and from our conversations I do believe this addresses the issue in question. I'm also all for splitting out responsibilities better into those other modules, so thanks for doing that! Looks good from my point of view.

File: KeenClient/KeenClient.m (hunk 2 above)
Comment (baumatron) [inline KeenClient/KeenClient.m]: I agree it can go away. This was an instance where I was just preserving what was already there to manage the scope of the change, but I'm ok with getting rid of it.

File: KeenClient/KeenClient.m (hunk 3 above)
Comment (baumatron) [inline KeenClient/KeenClient.m]: Good catch, that's not what's supposed to happen.

File: KeenClient/KeenClient.m (hunk 4 above)
Comment (baumatron) [inline KeenClient/KeenClient.m]: Nope, I'll change it to nil != writeKey, which I generally prefer since there isn't a type coercion and the intent is clearer.

File: KeenClient/KeenClient.m (hunk 5 above)
Comment (baumatron) [inline KeenClient/KeenClient.m]: Will fix.

File: KeenClient/KeenClient.m (hunk 10 above)
Comment (baumatron) [inline KeenClient/KeenClient.m]: It's still there, just moved it to KIOFileStore. Though I'd be willing to start a conversation about removing all of this stuff with the argument that the complexity isn't worth the use case it covers.

File: KeenClient/KeenClient.m (hunk 6 above)
Comment (baumatron) [inline KeenClient/KeenClient.m]: The logic here was actually redundant since runQuery: contains it as well.

File: KeenClient/KeenClient.m (hunk 7 above)
Comment (baumatron) [inline KeenClient/KeenClient.m]: Yep, and it was done by runQuery: already, so this was a redundant check.

Comment (baumatron) [inline KeenClient/KeenClient.m]: Yep.

File: KeenClientTests/KeenClientTests.m (hunk 8 above)
Comment (baumatron) [inline KeenClientTests/KeenClientTests.m]: I agree, we should just do that at some point.

File: KeenClient/KeenClient.h (hunk 9 above)
Comment (baumatron) [inline KeenClient/KeenClient.h]: That's the idea. I marked as deprecated anything in this change that seemed like it obviously should go, but couldn't because it would require a major version revision.

File: KeenClientTests/KeenClientTests.m (hunk 8 above)
Comment (masojus) [inline KeenClientTests/KeenClientTests.m]: Sold.

File: KeenClient/KeenClient.m (hunk 10 above)
Comment (masojus) [inline KeenClient/KeenClient.m]: I thought parts of this code were actually completely useless in that they weren't called anymore from anywhere. But yes, in general, the entire use case seems dubious.
